name: Build
on:
  push:
    branches: [ '**' ]
  
  workflow_dispatch:

jobs:
  build-and-commit:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
        - uses: actions/checkout@v2
        
        - name: Replacements
          run: |
            sed -i 's/src\/typewriter\./dist\/typewriter\.min\./g' examples.html
          
        
        - name: Auto Minify
          uses: nizarmah/auto-minify@v2.1
          with:
            directory: 'src'
            output: 'dist'
        - name: Auto committing minified files
          uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_message: "Github Action: Auto Minified JS and CSS files"
            branch: ${{ github.ref }}
